---
title: "Hire Me!"
---

### Potential Employers

I am currently looking for full time work in the broad fields of Data Science and Economics. [Check out my resume](/cv/index.qmd) and send me an email (cwiegand-_at_-uoregon-_dot_-edu) if you are interested and want to open up a conversation!

### Consulting & Contract Work

If you are in need of a PhD economist -- specifically one who specializes in game theory, behavioral economics, and consumer choice theory -- I am available for consulting work. My rate is negotiable but starts at $75/hr. I'd love to chat, just [send me an email](mailto:cwiegand@ureogon.edu).

Additionally, if you are looking for an economics litigation consultant, I encourage you to reach out. I am looking to expand this part of my portfolio, so my hourly rate is currently flexible negotiable.

If email is not your preferred mode of communication, [check out my linkedin](https://www.linkedin.com/in/connor-wiegand).


### Tutoring

I am currently available to tutor economics undergraduates for all levels of microeconomics and game theory. If you have tutoring needs outside of this, such as introductory macro or even calculus, please reach out. My tutoring rate starts at $50/hr.  